export const ONE_SECOND_IN_MS = 1000;
export const ONE_MINUTE_IN_MS = 60 * ONE_SECOND_IN_MS;
export const ONE_HOUR_IN_MS = 60 * ONE_MINUTE_IN_MS;
export const ONE_DAY_IN_MS = 24 * ONE_HOUR_IN_MS;
export const ONE_WEEK_IN_MS = 7 * ONE_DAY_IN_MS;
export const STANDARD_DEBOUNCE_DURATION = 1 * ONE_SECOND_IN_MS;
export const STANDARD_FORCE_DURATION = 10 * ONE_SECOND_IN_MS;
export const ANIMATION_SPEED_IN_MS = 350;
